spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/shoestoredb
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 372568875635-ecnjccde4m4lmfgs1cgvdl4f31q9os69.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 273667424896000
            client-secret: a2bc51f2cdf9937ae1c915d59374301b
            scope:
              - email
              - public_profile
server:
  port: '8091'

