package com.dacs.entitymodules.enumType;

public enum MailHelper {
    MAIL_USERNAME, MAIL_PORT, MAIL_FROM, MAIL_HOST, MAIL_PASSWORD, MAIL_SENDER_NAME,
    CUSTOMER_VERIFY_SUBJECT, CUSTOMER_VERIFY_CONTENT, SMTP_AUTH, SMTP_SECURED
}
